var ALBUMS = [
    {title:'Rubber Soul', slug:'rubber-soul', band:'The Beatles', side1: ['Drive My Car','Norwegian Wood (This Bird Has Flown)','You Won\'t See Me','Nowhere Man','Think for Yourself','The Word','Michelle'], side2: ['What Goes On','Girl','I\'m Looking Through You','In My Life','Wait','If I Needed Someone','Run for Your Life']},
    {title:'Sticky Fingers', slug:'sticky-fingers', band:'The Rolling Stones', side1: ['Brown Sugar','Sway','Wild Horses','Can\'t You Hear Me Knocking','You Gotta Move'], side2: ['Bitch','I Got the Blues','Sister Morphine','Dead Flowers','Moonlight Mile']},
    {title:'Blood on the Tracks', slug:'blood-on-the-tracks', band:'Bob Dylan', side1: ['Tangled Up in Blue','Simple Twist of Fate','You\'re a Big Girl Now','Idiot Wind','You\'re Gonna Make Me Lonesome When You Go'], side2: ['Meet Me in the Morning','Lily, Rosemary and the Jack of Hearts','If You See Her, Say Hello','Shelter from the Storm','Buckets of Rain']},
    {title:'Hunky Dory', slug:'hunky-dory', band:'David Bowie', side1: ['Changes','Oh! You Pretty Things','Eight Line Poem','Life on Mars?','Kooks','Quicksand'], side2: ['Fill Your Heart','Andy Warhol','Song for Bob Dylan','Queen Bitch','The Bewlay Brothers']},
    {title:'Lovesexy', slug:'lovesexy', band:'Prince', side1: ['Eye No','Alphabet St.','Glam Slam','Anna Stesia'], side2: ['Dance On','Lovesexy','When 2 R in Love','I Wish U Heaven','Positivity']},
    {title:'Thriller', slug:'thriller', band:'Michael Jackson', side1: ['Wanna Be Startin\' Somethin','Baby Be Mine','The Girl Is Mine','Thriller'], side2: ['Beat It','Billie Jean','Human Nature','P.Y.T. (Pretty Young Thing)','The Lady in My Life']},
    {title:'Blue', slug:'blue', band:'Joni Mitchell', side1: ['All I Want','My Old Man','Little Green','Carey','Blue'], side2: ['California','This Flight Tonight','River','A Case of You','The Last Time I Saw Richard']},
    {title:'At Last!', slug:'at-last', band:'Etta James', side1: ['Anything to Say You\'re Mine','My Dearest Darling','Trust in Me','A Sunday Kind of Love','Tough Mary'], side2: ['I Just Want to Make Love to You','At Last','All I Could Do Was Cry','Stormy Weather','Girl of My Dreams']},
    {title:'American Beauty', slug:'american-beauty', band:'Grateful Dead', side1: ['Box of Rain','Friend of the Devil','Sugar Magnolia','Operator','Candyman'], side2: ['Ripple','Brokedown Palace','Till the Morning Comes','Attics of My Life','Truckin\'']}
];
